# python-ci.yml
name: basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-run-pytest:

    runs-on: ubuntu-latest

    steps:
    # Checkout branch triggering event.
    - uses: actions/checkout@v3

    # Install python 3.10.6
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"

    # Install python packages using requirements file.
    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip cython wheel
        pip install -r requirements.txt

    # Run tests with Pytest.
    - name: Run tests
      run: make

